module.exports = {
  DEFAULT_ALARM_STRATEGY: 'default_alarm_strategy',
  CUSTOMER_ALARM_STRATEGY: 'customer_alarm_strategy',
  TEMP_ALARM_STRATEGY: 'temp_alarm_strategy',
  CONTACT: 'contact',
  DEVICE: 'device',
  MYEVENT: 'my_event',
  ROLE: 'role',
  SMARTGATE_ALARM_STRATEGY: 'smartgate_alarm_strategy',
  SMARTGATE: 'smartgate',
  USER: 'user',
  GEOGROUP:'geogroup',
  AIR_TH_AVERAGE_DATA: 'air_th_average_data',
  AIR_TH_DATA: 'air_th_data',
  SMARTGATE_DATA: 'smartgate_data',
  SMARTGATE_AVERAGE_DATA: 'smartgate_average_data',
  SOIL_TH_AVERAGE_DATA: 'soil_th_average_data',
  SOIL_TH_DATA: 'soil_th_data',
  CO_DATA:'co_data',
  CO_AVERAGE_DATA:'co_average_data',
  CO2_DATA:'co2_data',
  CO2_AVERAGE_DATA:'co2_average_data',
  LUX_DATA:'lux_data',
  LUX_AVERAGE_DATA:'lux_average_data',
  SMOKE_DATA: 'smoke_data',
  SMOKE_AVERAGE_DATA: 'smoke_average_data'
}